# Generated by Django 5.2.5 on 2026-02-18 17:05

from django.conf import settings
from django.db import migrations, models
from datetime import timedelta
from django.utils import timezone


def _normalize_weekly_windows_and_badges(apps, schema_editor):
    Leaderboard = apps.get_model('leaderboard', 'Leaderboard')
    Reward = apps.get_model('leaderboard', 'Reward')

    for entry in Leaderboard.objects.filter(scope='weekly', week_start__isnull=True).iterator():
        source_date = timezone.localtime(entry.updated_at).date() if entry.updated_at else timezone.localdate()
        week_start = source_date - timedelta(days=source_date.weekday())
        Leaderboard.objects.filter(pk=entry.pk).update(week_start=week_start)

    Leaderboard.objects.filter(scope='global').exclude(week_start__isnull=True).update(week_start=None)

    Reward.objects.filter(badge_icon='ðŸ…').update(badge_icon='\U0001f3c5')
    Reward.objects.filter(badge_icon='ðŸš€').update(badge_icon='\U0001f680')


def _noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboard',
            options={'ordering': ('-score', '-updated_at', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='leaderboard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='week_start',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='source_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='source_type',
            field=models.CharField(blank=True, choices=[('battle_win', 'Battle Win'), ('other', 'Other')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reward',
            name='badge_icon',
            field=models.CharField(default='\U0001f3c5', max_length=20),
        ),
        migrations.RunPython(_normalize_weekly_windows_and_badges, reverse_code=_noop_reverse),
        migrations.AddIndex(
            model_name='leaderboard',
            index=models.Index(fields=['scope', 'week_start', '-score', '-updated_at'], name='leaderboard_scope_b26206_idx'),
        ),
        migrations.AddConstraint(
            model_name='leaderboard',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'global')), fields=('user', 'scope'), name='uq_leaderboard_user_global_scope'),
        ),
        migrations.AddConstraint(
            model_name='leaderboard',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'weekly')), fields=('user', 'scope', 'week_start'), name='uq_leaderboard_user_weekly_scope_window'),
        ),
        migrations.AddConstraint(
            model_name='leaderboard',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='ck_leaderboard_score_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='leaderboard',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'global'), ('week_start__isnull', True)), models.Q(('scope', 'weekly'), ('week_start__isnull', False)), _connector='OR'), name='ck_leaderboard_week_scope_consistency'),
        ),
        migrations.AddConstraint(
            model_name='reward',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False), ('source_type__isnull', False)), fields=('user', 'source_type', 'source_id'), name='uq_reward_user_source'),
        ),
    ]
