# Generated by Django 5.2.5 on 2026-02-14 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('challenge_type', models.CharField(choices=[('algorithm', 'Algorithm'), ('quiz', 'Quiz'), ('aptitude', 'Placement Aptitude')], max_length=20)),
                ('algorithm_type', models.CharField(blank=True, choices=[('bfs', 'BFS'), ('dfs', 'DFS'), ('astar', 'A*'), ('minimax', 'Minimax')], default='', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('description', models.TextField()),
                ('prompt', models.TextField()),
                ('starter_code', models.TextField(blank=True)),
                ('expected_answer', models.CharField(blank=True, max_length=255)),
                ('visualization_payload', models.JSONField(blank=True, default=dict)),
                ('xp_reward', models.PositiveIntegerField(default=50)),
                ('max_score', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('submitted_answer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='challenges.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
