# Generated by Django 5.2.5 on 2026-02-14 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='algorithm_type',
            field=models.CharField(blank=True, choices=[('bfs', 'BFS'), ('dfs', 'DFS'), ('astar', 'A*'), ('minimax', 'Minimax'), ('bubble_sort', 'Bubble Sort'), ('selection_sort', 'Selection Sort'), ('insertion_sort', 'Insertion Sort'), ('merge_sort', 'Merge Sort'), ('quick_sort', 'Quick Sort'), ('heap_sort', 'Heap Sort'), ('linear_search', 'Linear Search'), ('binary_search', 'Binary Search'), ('dijkstra', 'Dijkstra'), ('bst', 'Binary Search Tree'), ('knapsack', 'Knapsack'), ('lcs', 'Longest Common Subsequence'), ('activity_selection', 'Activity Selection'), ('linear_regression', 'Linear Regression'), ('logistic_regression', 'Logistic Regression'), ('kmeans', 'K-Means'), ('knn', 'K-Nearest Neighbors'), ('decision_tree', 'Decision Tree'), ('naive_bayes', 'Naive Bayes'), ('neural_network', 'Neural Network')], default='', max_length=20),
        ),
    ]
