# Generated by Django 5.2.11 on 2026-02-15 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_topic_and_userchallengeprog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ('topic_id', 'order_index')},
        ),
        migrations.AlterUniqueTogether(
            name='challenge',
            unique_together={('topic', 'order_index')},
        ),
    ]
