# Generated by Codex on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challengeattempt_attempt_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='battle_score_applied',
            field=models.BooleanField(default=False),
        ),
    ]
