# Generated by Django 5.2.5 on 2026-02-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_challengeattempt_battle_score_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='algorithm_type',
            field=models.CharField(blank=True, choices=[('linked_list', 'Linked List'), ('doubly_linked_list', 'Doubly Linked List'), ('circular_linked_list', 'Circular Linked List'), ('stack', 'Stack'), ('queue', 'Queue'), ('bfs', 'BFS'), ('dfs', 'DFS'), ('astar', 'A*'), ('minimax', 'Minimax'), ('bubble_sort', 'Bubble Sort'), ('selection_sort', 'Selection Sort'), ('insertion_sort', 'Insertion Sort'), ('merge_sort', 'Merge Sort'), ('quick_sort', 'Quick Sort'), ('heap_sort', 'Heap Sort'), ('linear_search', 'Linear Search'), ('binary_search', 'Binary Search'), ('dijkstra', 'Dijkstra'), ('bst', 'Binary Search Tree'), ('knapsack', 'Knapsack'), ('lcs', 'Longest Common Subsequence'), ('activity_selection', 'Activity Selection'), ('linear_regression', 'Linear Regression'), ('logistic_regression', 'Logistic Regression'), ('kmeans', 'K-Means'), ('knn', 'K-Nearest Neighbors'), ('decision_tree', 'Decision Tree'), ('naive_bayes', 'Naive Bayes'), ('neural_network', 'Neural Network'), ('backtracking', 'Backtracking'), ('recursion', 'Recursion'), ('string_algorithm', 'String Algorithm'), ('math_algorithm', 'Math Algorithm'), ('bit_conversion', 'Bit Conversion'), ('array_algorithm', 'Array Algorithm'), ('hashing_algorithm', 'Hashing Algorithm')], default='', max_length=20),
        ),
    ]
