# Generated by Codex on 2026-03-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_alter_challenge_algorithm_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='challengeattempt',
            constraint=models.UniqueConstraint(
                fields=('user', 'challenge', 'attempt_index'),
                name='unique_attempt_index_per_user_challenge',
            ),
        ),
    ]
