# Generated by Django 5.2.11 on 2026-03-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_challengeattempt_unique_attempt_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
