# Generated by Django 5.2.5 on 2026-02-18 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
        ('challenges', '0005_challengeattempt_attempt_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlematch',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_matches', to='challenges.challenge'),
        ),
        migrations.AddField(
            model_name='battlematch',
            name='preferred_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battle_matches', to='challenges.topic'),
        ),
    ]
